#######################################
# PHP Debugger (xdebug|blackfire|none)

PHP_DEBUGGER=none

#######################################
# Context environment

# TYPO3
TYPO3_CONTEXT=Development/Docker

# Symfony
SYMFONY_ENV=dev
SYMFONY_DEBUG=0

# CakePHP
CAKE_ENV=dev

# yii
YII_ENVIRONMENT=Development

